a = ['kenil','meet','harshit','ayush','kano']
# a.append('hello')
# a.clear()
# b=a.copy()
# b=a.count('k')
# b=a.index('harshit')
# a.insert(4,'hello')
# a.pop(4)
# a.remove('hello')
# a.reverse()
a.sort()
print(a)